#!/bin/bash
# concourse-deploy-docker-resource in

set -e              # Will exit immediate if command exits with non-zero status
set -u              # Will print message if variable not set,
# set -x            # Prints the shell commands +
set -o pipefail     # Fail on a pipline like cmd1 | cmd2 | cmd3, rather then wait

exec 3>&1           # Make stdout available as fd 3 for the result
exec 1>&2           # Redirect all output to stderr for logging

# WHAT IS THIS?
echo "IN - GET"
echo "I made the version 0.0.5 to make this easy"
echo ""

# CURRENT DIRECTORY
echo "pwd is"
pwd 
echo ""
echo "ls directory"
ls -lat 
echo ""

# CD WORKING DIRECTORY
WORKING_DIR=$1
echo "WORKING_DIR = $WORKING_DIR"
cd "$WORKING_DIR"
echo "pwd is"
pwd 
echo ""
echo "ls directory"
ls -lat 
echo ""

# REMEMBER WE ADDED TREE BINARY INTO THE BUILD.
# echo "tree - Not sure there is anything to show here."
# tree
# echo ""

echo "PART 1 - INPUT ********************************************************************************"
echo "parse stdin"
echo ""

# READ stdin (which is json paramter) TO A FILE
# -M = Monochrome output
# -S = Sort order
# . =  get everything
jq -M -S . <&0 | tee get_input.json >/dev/null    # tee redirects to a file.

echo "json stdin is:"
cat get_input.json
echo ""

# PARSE THE JSON FILE get_input.json 
username=$(jq -r .source.username < get_input.json)
password=$(jq -r .source.password < get_input.json)
#param1=$(jq -r .params.param1 < get_input.json)
#param2=$(jq -r .params.param2 < get_input.json)
#param3=$(jq -r .params.param3 < get_input.json)
input_version=$(jq -r .version.ref < get_input.json)

# PRINT OUT THE INPUT
echo "source are:"
echo "    $username"
echo "    $password"
#echo "params are:"
#echo "    $param1"
#echo "    $param2"
#echo "    $param3"
echo "version is:"
echo "    $input_version"
echo ""

# SOME METATDATA
echo "BUILD_ID = $BUILD_ID"
echo "BUILD_NAME = $BUILD_NAME"
echo "BUILD_JOB_NAME = $BUILD_JOB_NAME"
echo "BUILD_PIPELINE_NAME = $BUILD_PIPELINE_NAME"
echo "ATC_EXTERNAL_URL = $ATC_EXTERNAL_URL"
echo ""

echo "PART 2 - GET SOMETHING ************************************************************************"
echo "Really nothing to get, but I'll get the tag from dockerhub for fun"
echo "You have the source, params and fectched what you needed"
echo ""

# MIMIC - MUST GET SAME VERSION TO CHECK
# **************
version=$input_version
# **************

# GET DOCKERHUB TOKEN
TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "'$username'", "password": "'$password'"}' https://hub.docker.com/v2/users/login/ | jq -r .token)

# GET DOCKERHUB TAGS
IMAGE_TAG=$(curl -s -H "Authorization: JWT ${TOKEN}" https://hub.docker.com/v2/repositories/$username/concourse-deploy-docker-resource/tags/?page_size=100 | jq -r '.results|.[]|.name')
echo "The docker image tag is $IMAGE_TAG"
echo ""

# MIMIC FETCH - CREATE A JSON FILE
json_get_fetch='{
    "version": { 
        "ref": "'$version'" 
    },
    "author": "Jeff DeCola",
    "image_tag": "'$IMAGE_TAG'"
}'
jq -n "$json_get_fetch" > get_fetch.json

echo "cat get_fetch.json"
cat get_fetch.json
echo ""

# PARSE THE JSON FILE get_fetch.json 
version=$(jq -r .version.ref < get_fetch.json)
author=$(jq -r .author < get_fetch.json)
imagetag=$(jq -r .image_tag < get_fetch.json)

# PRINT OUT THE FETCH
echo " version      $version"
echo " author       $author"
echo " image_tag    $imagetag"
echo ""

echo "ls directory"
ls -lat 
echo ""

echo "PART 3 - OUTPUT *******************************************************************************"
echo "send stdout"
echo ""

# CREATE OUTPUT
json_get_output='{
    "version":{ "ref": "'$version'" },
    "metadata": [
        { "name": "author", "value": "'$author'" },
        { "name": "executable", "value": "in" },
        { "name": "version", "value": "'$version'" },
        { "name": "image_tag", "value": "'$imagetag'" }
    ]
}'
jq -n "$json_get_output" > get_output.json

echo "json stdout is:"
cat get_output.json
echo ""

echo "ls directory"
ls -lat 
echo ""

# OUTPUT JSON TO STDOUT
# -n don't read any input at all.  Construct froms scratch.
jq -n "$json_get_output" >&3
