#!/bin/bash
# concourse-deploy-docker-resource in

set -e              # Will exit immediate if command exits with non-zero status
set -u              # Will print message if variable not set,
# set -x            # Prints the shell commands +
set -o pipefail     # Fail on a pipline like cmd1 | cmd2 | cmd3, rather then wait

exec 3>&1           # Make stdout available as fd 3 for the result
exec 1>&2           # Redirect all output to stderr for logging

# WHAT IS THIS?
echo "OUT - PUT"
echo "I made the version 0.0.5 to make this easy"
echo ""

# CURRENT DIRECTORY
echo "pwd is"
pwd 
echo ""
echo "ls directory"
ls -lat 
echo ""

# CD WORKING DIRECTORY
WORKING_DIR=$1
echo "WORKING_DIR = $WORKING_DIR"
cd "$WORKING_DIR"
echo "pwd is"
pwd 
echo ""
echo "ls directory"
ls -lat 
echo ""

# REMEMBER WE ADDED TREE BINARY INTO THE BUILD.
#echo "tree - Not sure there is anything to show here."
#tree
#echo ""

echo "PART 1 - INPUT ********************************************************************************"
echo "parse stdin"
echo ""

# READ stdin (which is json paramter) TO A FILE
# -M = Monochrome output
# -S = Sort order
# . =  get everything
jq -M -S . <&0 | tee put_input.json >/dev/null    # tee redirects to a file.

echo "json stdin is:"
cat put_input.json
echo ""

# PARSE THE JSON FILE put_input.json 
username=$(jq -r .source.username < get_input.json)
password=$(jq -r .source.password < get_input.json)

docker_host_ip=$(jq -r .source.DOCKER_HOST_IP < put_input.json)
docer_host_port=$(jq -r .source.DOCKER_HOST_PORT < put_input.json)
docker_host_user=$(jq -r .source.DOCKER_HOST_USER < put_input.json)
docker_host_ssh_private_key_file=$(jq -r .source.DOCKER_HOST_SSH_PRIVATE_KEY_FILE < put_input.json)

# PRINT OUT THE INPUT
echo "source are:"
echo "    $username"
echo "    $password"
echo "params are:"
echo "    $docker_host_ip"
echo "    $docer_host_port"
echo "    $docker_host_user"
echo "    $docker_host_ssh_private_key_file"
echo ""

# SOME METATDATA
echo "BUILD_ID = $BUILD_ID"
echo "BUILD_NAME = $BUILD_NAME"
echo "BUILD_JOB_NAME = $BUILD_JOB_NAME"
echo "BUILD_PIPELINE_NAME = $BUILD_PIPELINE_NAME"
echo "ATC_EXTERNAL_URL = $ATC_EXTERNAL_URL"
echo ""

echo "PART 2 - PUT SOMETHING ************************************************************************"
echo "Mimic a put and place a put_fetch.json file in the working directory"
echo "You have the source, params"
echo ""

# MIMIC - MUST GET SAME VERSION TO CHECK - THIS IS NOT PASSED
# **************
version=v0.0.5
# **************

# MIMIC FETCH - CREATE A JSON FILE
json_put_fetch='{
    "version": { 
        "ref": "'$version'" 
    },
    "author": "Jeff DeCola"
}'
jq -n "$json_put_fetch" > put_fetch.json

echo "cat put_fetch.json"
cat put_fetch.json
echo ""

# PARSE THE JSON FILE put_fetch.json 
version=$(jq -r .version.ref < put_fetch.json)
author=$(jq -r .author < put_fetch.json)

# PRINT OUT THE FETCH
echo " version      $version"
echo " author       $author"
echo ""

echo "ls directory"
ls -lat 
echo ""

echo "PART 3 - OUTPUT *******************************************************************************"
echo "send stdout"
echo ""

# CREATE OUTPUT
json_put_output='{
    "version":{ "ref": "'$version'" },
    "metadata": [
        { "name": "author", "value": "'$author'" },
        { "name": "executable", "value": "out" },
        { "name": "version", "value": "'$version'" }
    ]
}'
jq -n "$json_put_output" > put_output.json

echo "json stdout is:"
cat put_output.json
echo ""

echo "ls directory"
ls -lat 
echo ""

# OUTPUT JSON TO STDOUT
# -n don't read any input at all.  Construct froms scratch.
jq -n "$json_put_output" >&3
