# concourse-deploy-docker-resource test-this-resource pipeline.yml

#------------------------------------------------------------------------------------------
jobs:

#**********************************************
- name: job-test-concourse-deploy-docker-resource
#**********************************************
  plan:

    # GET REPO FROM GITHUB
    - get: concourse-deploy-docker-resource
      trigger: true

    # CONCOURSE RESOURCE TEMPLATE
    - get: jeffs-test-resource
      params:
        param1: "get param1"
        param2: "get param2" 
        param3: "get param3" 

    # RUN TASK IN REPO USING ALPINE DOCKER IMAGE
    - task: task-test-concourse-deploy-docker-resource
      file: concourse-deploy-docker-resource/test-this-resource/tasks/task-test-concourse-deploy-docker-resource.yml

      # TASK SUCCESS
      on_success:
        do:
          # CONCOURSE RESOURCE TEMPLATE
          - put: jeffs-test-resource
            params:
              param1: "put param1"
              param2: "put param2"    
              param3: "put param3"    

#------------------------------------------------------------------------------------------
resource_types:

  - name: jeffs-resource
    type: docker-image
    source:
      repository: jeffdecola/concourse-deploy-docker-resource
      tag: latest

#------------------------------------------------------------------------------------------
resources:

  - name: concourse-deploy-docker-resource
    type: git
    icon: docker
    source:
      uri: git@github.com:jeffdecola/concourse-deploy-docker-resource.git
      branch: master
      private_key: ((git_private_key))
      
  - name: jeffs-test-resource
    type: jeffs-resource
    icon: magnify
    source:
      source1: "source1 info"
      source2: "source2 info"
      source3: "source3 info"
