# concourse-deploy-docker-resource test-this-resource pipeline.yml

#------------------------------------------------------------------------------------------
jobs:

#**********************************************
- name: job-test-concourse-deploy-docker-resource
#**********************************************
  plan:

    # GET REPO FROM GITHUB
    - get: concourse-deploy-docker-resource
      trigger: true

    # CONCOURSE RESOURCE TEMPLATE
    - get: test-resource-deploy-docker

    # RUN TASK IN REPO USING ALPINE DOCKER IMAGE (DON'T NEED THIS)
    - task: task-test-concourse-deploy-docker-resource
      file: concourse-deploy-docker-resource/test-this-resource/tasks/task-test-concourse-deploy-docker-resource.yml

      # TASK SUCCESS
      on_success:
        do:
          # CONCOURSE RESOURCE TEMPLATE
          - put: test-resource-deploy-docker
            params:
              DOCKER_HOST_SSH_PRIVATE_KEY_FILE: {{docker_host_ssh_private_key_file}}
              DOCKER_HOST_PORT: '22'
              DOCKER_HOST_USER: 'jeffry'
              DOCKER_HOST_IP: '192.168.20.122'

#------------------------------------------------------------------------------------------
resource_types:

  - name: deploy-docker
    type: docker-image
    source:
      repository: jeffdecola/concourse-deploy-docker-resource
      tag: latest

#------------------------------------------------------------------------------------------
resources:

  - name: concourse-deploy-docker-resource
    type: git
    icon: docker
    source:
      uri: git@github.com:jeffdecola/concourse-deploy-docker-resource.git
      branch: main
      private_key: ((git_private_key))
      
  - name: test-resource-deploy-docker
    type: deploy-docker
    icon: magnify
    source:
      username: jeffdecola
      password: ((dockerhub_password))

