# concourse-deploy-docker-resource pipeline.yml

#------------------------------------------------------------------------------------------
jobs:

#**********************************************
- name: job-readme-github-pages
#**********************************************
  plan:

    # GET REPO FROM GITHUB
    - get: concourse-deploy-docker-resource
      trigger: true
    # SEND SLACK ALERT  
    - put: resource-slack-alert
      params:
        channel: '#jeff-builds'
        text: "From concourse-deploy-docker-resource: STARTED job-readme-github-pages in concourse ci."
    # SEND GITHUB STATUS
    - put: resource-repo-status
      params: { state: "pending", description: "STARTED job-readme-github-pages in concourse ci.", commit: "concourse-deploy-docker-resource" }    
    
    # RUN TASK IN REPO USING ALPINE DOCKER IMAGE
    - task: task-readme-github-pages
      file: concourse-deploy-docker-resource/ci/tasks/task-readme-github-pages.yml
      
      # TASK SUCCESS
      on_success:
        do:
          # PUSH NEW REPO TO GITHUB
          - put: concourse-deploy-docker-resource
            params:
              repository: concourse-deploy-docker-resource-updated  
          # SEND SLACK ALERT  
          - put: resource-slack-alert
            params:
              channel: '#jeff-builds'
              text: "From concourse-deploy-docker-resource: PASSED job-readme-github-pages in concourse ci."
          # SEND GITHUB STATUS
          - put: resource-repo-status
            params: { state: "success", description: "PASSED job-readme-github-pages in concourse ci", commit: "concourse-deploy-docker-resource" }
      
      # TASK FAILURE   
      on_failure:
        do:
          # SEND SLACK ALERT  
          - put: resource-slack-alert
            params:
              channel: '#jeff-builds'
              text: "From concourse-deploy-docker-resource: FAILED job-readme-github-pages in concourse ci."
          # SEND GITHUB STATUS
          - put: resource-repo-status
            params: { state: "failure", description: "FAILED job-readme-github-pages in concourse ci", commit: "concourse-deploy-docker-resource" }

#**********************************************
- name: job-build-push
#**********************************************
  plan:

    # GET REPO FROM GITHUB
    - get: concourse-deploy-docker-resource
      trigger: true
      passed: [job-readme-github-pages]
    # SEND SLACK ALERT  
    - put: resource-slack-alert
      params:
        channel: '#jeff-builds'
        text: "From concourse-deploy-docker-resource: STARTED job-build-push in concourse ci."
    # SEND GITHUB STATUS
    - put: resource-repo-status
      params: { state: "pending", description: "STARTED job-build-push in concourse ci.", commit: "concourse-deploy-docker-resource" }

    # RUN TASK IN REPO USING ALPINE DOCKER IMAGE 
    - task: task-build-push
      file: concourse-deploy-docker-resource/ci/tasks/task-build-push.yml

    # PUSH DOCKER IMAGE TO DOCKERHUB  
    - put: resource-dump-to-dockerhub
      params: { build: "dist"}
      
      # TASK SUCCESS
      on_success:
        do:
          # SEND SLACK ALERT  
          - put: resource-slack-alert
            params:
              channel: '#jeff-builds'
              text: "From concourse-deploy-docker-resource: PASSED job-build-push in concourse ci."
          # SEND GITHUB STATUS
          - put: resource-repo-status
            params: { state: "success", description: "PASSED job-build-push in concourse ci.", commit: "concourse-deploy-docker-resource" }
      
      # TASK FAILURE    
      on_failure:
        do:
          # SEND SLACK ALERT  
          - put: resource-slack-alert
            params:
              channel: '#jeff-builds'
              text: "From concourse-deploy-docker-resource: FAILED job-build-push in concourse ci."
          # SEND GITHUB STATUS
          - put: resource-repo-status
            params: { state: "failure", description: "FAILED job-build-push in concourse ci.", commit: "concourse-deploy-docker-resource" }

#------------------------------------------------------------------------------------------
resource_types:

  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

  - name: github-status
    type: docker-image
    source:
      repository: jeffdecola/github-status-resource-clone
      tag: v0.0.2

#------------------------------------------------------------------------------------------
resources:

  - name: concourse-deploy-docker-resource
    type: git
    icon: github
    source:
      #uri: https://github.com/jeffdecola/concourse-deploy-docker-resource
      uri: git@github.com:jeffdecola/concourse-deploy-docker-resource.git
      branch: main
      private_key: ((git_private_key))

  - name: resource-dump-to-dockerhub
    type: docker-image
    icon: docker
    source:
      repository: jeffdecola/concourse-deploy-docker-resource
      tag: latest
      username: jeffdecola
      password: ((dockerhub_password))

  - name: resource-slack-alert
    type: slack-notification
    icon: slack
    source:
      url: ((slack_url)) 

  - name: resource-repo-status
    type: github-status
    icon: github
    source:
      repository: jeffdecola/concourse-deploy-docker-resource 
      access_token: ((repo_github_token))
      branch: main
